language: go

sudo: required
services:
    - docker

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y asciidoc
    - git clone https://github.com/ioi/isolate
    - pushd isolate && make && sudo make install && popd
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
